typography_spectrum: 0.49229458859190345
color:
  brandStrength: 0.10120724979788065
  lightness: 0.7045392475556582
  saturation: 0.6822651079855859
  rhythmicContrast: 0.17892460920847952
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.12636984582059085
name: agerbeek
title: keebregA
